title: Servicio de Gestión de Stock
description: Servicio para la Gestión de Inventario, Control de Stock y Movimientos de Almacén
theme: jekyll-theme-cayman

# Configuración de Jekyll
defaults:
  -
    scope:
      path: "" # aplica a todos los archivos
    values:
      layout: default

# Configuración de Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configuración de la página principal
index_page: index.md 